<?php

namespace Container82To3zg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SBqSQkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SBq_SQk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SBq_SQk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carrezRepository' => ['privates', 'App\\Repository\\CarrezRepository', 'getCarrezRepositoryService', true],
        ], [
            'carrezRepository' => 'App\\Repository\\CarrezRepository',
        ]);
    }
}
