<?php

namespace Container82To3zg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1qRlNrCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1qRlNrC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1qRlNrC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'termitesRepository' => ['privates', 'App\\Repository\\TermitesRepository', 'getTermitesRepositoryService', true],
        ], [
            'termitesRepository' => 'App\\Repository\\TermitesRepository',
        ]);
    }
}
