<?php

namespace ContainerRtUvGcC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M8o6KQMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m8o6KQM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m8o6KQM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'missionsRepository' => ['privates', 'App\\Repository\\MissionsRepository', 'getMissionsRepositoryService', true],
        ], [
            'missionsRepository' => 'App\\Repository\\MissionsRepository',
        ]);
    }
}
