<?php

namespace ContainerBQv7467;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1yis_H7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1yis.H7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1yis.H7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'asbestosRepository' => ['privates', 'App\\Repository\\AsbestosRepository', 'getAsbestosRepositoryService', true],
        ], [
            'asbestosRepository' => 'App\\Repository\\AsbestosRepository',
        ]);
    }
}
