<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJyz6ZBF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJyz6ZBF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJyz6ZBF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJyz6ZBF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJyz6ZBF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jyz6ZBF',
    'container.build_id' => '87fce58f',
    'container.build_time' => 1706175771,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJyz6ZBF');
