<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4HO4LvM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4HO4LvM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4HO4LvM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4HO4LvM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4HO4LvM\App_KernelDevDebugContainer([
    'container.build_hash' => '4HO4LvM',
    'container.build_id' => '10209c40',
    'container.build_time' => 1708938551,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4HO4LvM');
