<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container82To3zg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container82To3zg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container82To3zg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container82To3zg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container82To3zg\App_KernelDevDebugContainer([
    'container.build_hash' => '82To3zg',
    'container.build_id' => '55b9d05a',
    'container.build_time' => 1711110886,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container82To3zg');
