<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_assets' => [[], ['_controller' => 'App\\Controller\\AssetsController::index'], [], [['text', '/assets']], [], [], []],
    'app_condominium' => [[], ['_controller' => 'App\\Controller\\CondominiumController::index'], [], [['text', '/condominium']], [], [], []],
    'app_contacts' => [[], ['_controller' => 'App\\Controller\\ContactsController::index'], [], [['text', '/contacts']], [], [], []],
    'app_estimate' => [[], ['_controller' => 'App\\Controller\\EstimateController::index'], [], [['text', '/estimate']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
    'app_intervention_sector' => [[], ['_controller' => 'App\\Controller\\InterventionSectorController::index'], [], [['text', '/intervention/sector']], [], [], []],
    'app_missions' => [[], ['_controller' => 'App\\Controller\\MissionsController::index'], [], [['text', '/missions']], [], [], []],
    'app_post_construction' => [[], ['_controller' => 'App\\Controller\\PostConstructionController::index'], [], [['text', '/post/construction']], [], [], []],
    'app_pre_construction' => [[], ['_controller' => 'App\\Controller\\PreConstructionController::index'], [], [['text', '/pre/construction']], [], [], []],
    'app_pre_destruction' => [[], ['_controller' => 'App\\Controller\\PreDestructionController::index'], [], [['text', '/pre/destruction']], [], [], []],
    'app_pre_rent' => [[], ['_controller' => 'App\\Controller\\PreRentController::index'], [], [['text', '/pre/rent']], [], [], []],
    'app_pre_sell' => [[], ['_controller' => 'App\\Controller\\PreSellController::index'], [], [['text', '/pre/sell']], [], [], []],
    'app_skills' => [[], ['_controller' => 'App\\Controller\\SkillsController::index'], [], [['text', '/skills']], [], [], []],
    'App\Controller\AssetsController::index' => [[], ['_controller' => 'App\\Controller\\AssetsController::index'], [], [['text', '/assets']], [], [], []],
    'App\Controller\CondominiumController::index' => [[], ['_controller' => 'App\\Controller\\CondominiumController::index'], [], [['text', '/condominium']], [], [], []],
    'App\Controller\ContactsController::index' => [[], ['_controller' => 'App\\Controller\\ContactsController::index'], [], [['text', '/contacts']], [], [], []],
    'App\Controller\EstimateController::index' => [[], ['_controller' => 'App\\Controller\\EstimateController::index'], [], [['text', '/estimate']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
    'App\Controller\InterventionSectorController::index' => [[], ['_controller' => 'App\\Controller\\InterventionSectorController::index'], [], [['text', '/intervention/sector']], [], [], []],
    'App\Controller\MissionsController::index' => [[], ['_controller' => 'App\\Controller\\MissionsController::index'], [], [['text', '/missions']], [], [], []],
    'App\Controller\PostConstructionController::index' => [[], ['_controller' => 'App\\Controller\\PostConstructionController::index'], [], [['text', '/post/construction']], [], [], []],
    'App\Controller\PreConstructionController::index' => [[], ['_controller' => 'App\\Controller\\PreConstructionController::index'], [], [['text', '/pre/construction']], [], [], []],
    'App\Controller\PreDestructionController::index' => [[], ['_controller' => 'App\\Controller\\PreDestructionController::index'], [], [['text', '/pre/destruction']], [], [], []],
    'App\Controller\PreRentController::index' => [[], ['_controller' => 'App\\Controller\\PreRentController::index'], [], [['text', '/pre/rent']], [], [], []],
    'App\Controller\PreSellController::index' => [[], ['_controller' => 'App\\Controller\\PreSellController::index'], [], [['text', '/pre/sell']], [], [], []],
    'App\Controller\SkillsController::index' => [[], ['_controller' => 'App\\Controller\\SkillsController::index'], [], [['text', '/skills']], [], [], []],
];
