<?php

namespace ContainerOv3YclZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PbH6Uu6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PbH6Uu6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PbH6Uu6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'homePage' => ['privates', 'App\\Entity\\HomePage', NULL, 'Cannot autowire service "App\\Entity\\HomePage": argument "$config" of method "Doctrine\\ORM\\EntityManager::__construct()" references class "Doctrine\\ORM\\Configuration" but no such service exists. You should maybe alias this class to the existing "doctrine.orm.default_configuration" service.'],
        ], [
            'entityManager' => '?',
            'homePage' => 'App\\Entity\\HomePage',
        ]);
    }
}
