<?php

namespace ContainerOv3YclZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomePageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\HomePage' shared autowired service.
     *
     * @return \App\Entity\HomePage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Entity\\HomePage": argument "$config" of method "Doctrine\\ORM\\EntityManager::__construct()" references class "Doctrine\\ORM\\Configuration" but no such service exists. You should maybe alias this class to the existing "doctrine.orm.default_configuration" service.');
    }
}
